# Date and Time
MIN_VALUE = 0

SECS_IN_MINUTE = 60
MINS_IN_HOUR = 60
HOURS_IN_DAY = 24

DATETIME_FORMAT = "%H:%M:%S %d.%m.%Y"


# Field rules
SMALL_CHAR_LEN_FIELD = 60
CHOICES_LEN_FIELD = 10


# Machine parameters
CPU_CODE_NAME = "cpu"
MEM_CODE_NAME = "mem"
DISK_CODE_NAME = "disk"

COUNT_MACHINES = 30

DEFAULT_INTERVAL_IN_MINUTES = 15
DEFAULT_INTERVAL_IN_SECONDS = DEFAULT_INTERVAL_IN_MINUTES * SECS_IN_MINUTE
DEFAULT_CONCURRENSY_LIMIT = 30
TIMEOUT_IN_SECONDS = 10

CPU_MIN_VALUE_IN_PERCENTS = 1
MEM_MIN_VALUE_IN_PERCENTS = 5
DISK_MIN_VALUE_IN_PERCENTS = 10

MAX_VALUE_IN_PERCENTS = 100

CPU_LIMIT_IN_PERCENTS = 85

MEM_LIMIT_IN_PERCENTS = 90
MEM_LIMIT_TIME_IN_MINS = 30

DISK_LIMIT_IN_PERCENTS = 95
DISK_LIMIT_TIME_IN_HOURS = 2


# Polling Host settings
PORT = 8001
HOST = '127.0.0.1'
