# Generated by Django 5.2.6 on 2025-09-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={"ordering": ("-detected_at",)},
        ),
        migrations.AlterModelOptions(
            name="metric",
            options={"ordering": ("-requested_at",)},
        ),
        migrations.RenameField(
            model_name="incident",
            old_name="started_at",
            new_name="detected_at",
        ),
        migrations.RenameField(
            model_name="incident",
            old_name="type",
            new_name="overload_type",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="ended_at",
        ),
    ]
